name: Release Tarball

on:
  push:
    tags:
      - "v*.*.*"  # Trigger on tags following semantic versioning, e.g., v1.0.0

jobs:
  create-release:
    name: Generate and Publish Tarball
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Extract the version from the tag
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Create a versioned tar.gz archive
      - name: Create tar.gz archive
        run: |
          mkdir -p dist
          git archive --format=tar.gz -o dist/${VERSION}.tar.gz HEAD

      # Create a GitHub Release and upload the tar.gz file
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          assets: dist/${VERSION}.tar.gz
